<a href="https://colab.research.google.com/github/Shaurya8008/Skills/blob/main/NumPy_Pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy:It is a python library


1.  Numpy provides efficient storage
2.   It also provides better ways of handeling data for process
3. It is fast
4. It is easy to learn
5. Numpy uses relatively less memory to store data.




In [2]:
import numpy as np

In [3]:
myarr=np.array([[3,6,32,7]])

In [4]:
myarr[0,1]

np.int64(6)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]=45

In [8]:
myarr

array([[ 3, 45, 32,  7]])

**Array conversion from other Python Structures**

In [9]:
listarray=np.array([[1,2,3],[5,8,5],[6,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [6, 8, 9]])

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,65,78})

array({65, 34, 78}, dtype=object)

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng=np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,50,10)

In [21]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
emp=np.empty((4,6))

In [25]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [26]:
ide= np.identity(50)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
arr= np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr=arr.reshape(3,33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

#Axis


1D array has one axis

2D array has 2 axis

In [34]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [35]:
ar=np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
ar.sum(axis=0)

array([12, 15, 18])

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
8
9


In [43]:
ar.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

72

In [46]:
one=np.array([1,2,4,5,65,6])

In [47]:
one.argmax()

np.int64(4)

In [48]:
one.argmin()

np.int64(0)

In [49]:
one.argsort()

array([0, 1, 2, 3, 5, 4])

In [50]:
np.where(one>5)

(array([4, 5]),)

#Jupyter notebook


Jupiter Notebook: It is an open source application that allows you to create and share documents that contain live code , equations, visualisation and narrative text.


1.  It supports for over 40 programming language , including python ,julia and scala.
2.  It can be shared with other using mail,dropbox,githuband the jupyter notebook viewer.
3. Your code can produce rich interactive output HTML images,videos LaTex and custom MIME types

